app/config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from config import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('posts/', include('posts.urls')),
    path('', views.index, name='index'),
    path('members/', include('members.urls')),
] + static(
    prefix='/media/',
    document_root=settings.MEDIA_ROOT,
    )

app/members/urls.py
from django.urls import path

from members import views

app_name = 'members'
urlpatterns = [
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('signup/', views.signup, name='signup'),
    path('<int:pk>/my_info', views.my_info, name='my-info'),
    path('<int:pk>/user_info', views.user_info, name='user-info'),
    path('<int:pk>/withdraw/', views.withdraw, name='withdraw'),
    path('<int:pk>/follow_toggle', views.follow_toggle, name='follow'),
    path('<int:pk>/user_info/followers', views.follower_list, name='followers'),
    path('<int:pk>/user_info/followings', views.following_list, name='followings')

]

app/posts/urls.py
from django.urls import path

from posts import views

app_name = 'posts'
urlpatterns = [
    path('', views.post_list, name='post-list'),
    path('<int:pk>/', views.post_detail, name='post-detail'),
    path('post_create/', views.post_create, name='post-create'),
    path('<int:pk>/post_delete/', views.post_delete, name='post-delete'),
    path('<int:pk>/comment_create/', views.comment_create, name='comment-create'),
    path('<int:pk>/post_like', views.post_like, name='post-like'),

]

app/posts/models.py
from django.conf import settings
from django.db import models

from members.models import User


class Post(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    photo = models.ImageField(upload_to='post', blank=True)
    content = models.TextField(blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    like_users_at_post = models.ManyToManyField(
        settings.AUTH_USER_MODEL,
        blank=True,
        # 내가 좋아요를 누른 Post목록
        related_name='like_posts',
    )
    class Meta:
        ordering = ['-pk']

    def __str__(self):
        return f'{self.author}님의 게시물'

    @property
    def like_users(self):
        pl_qs = PostLike.objects.filter(post=self)
        users = list()
        for pl in pl_qs:
            users.append(pl.user)
        return users


class Comment(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='user_comment')
    post = models.ForeignKey(Post, on_delete=models.CASCADE,related_name='comments')
    comment = models.CharField(max_length=200)

    class Meta:
        ordering = ['-comment']

    def __str__(self):
        return f'{self.user}님의 댓글'


class PostLike(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)

app/posts/forms.py
from django import forms
from django.forms import ModelForm

from posts.models import Post


class PostCreate(forms.Form):
    photo = forms.ImageField(label='사진')
    content = forms.CharField(label='남기는 말', widget=forms.TextInput(
        attrs={
            'class': 'form-control',
        }
    ))

    def create_post(self, user):
        photo = self.cleaned_data['photo']
        content = self.cleaned_data['content']
        post = Post.objects.create(author=user, photo=photo, content=content)
        return post


class PostModelForm(ModelForm):

    class Meta:
        model = Post
        fields = [ 'photo', 'content']

app/posts/views/comment_create.py
from django.contrib.auth import get_user_model
from django.shortcuts import redirect

from ..models import Comment, Post

all = (
    'comment_create'
)

User = get_user_model()


def comment_create(request, pk):
    if request.method == 'POST':
        Comment.objects.create(
            user=request.user,
            post=Post.objects.get(pk=pk),
            comment=request.POST['comment'],
        )
        return redirect('posts:post-list')

app/posts/views/post_create.py
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from django.shortcuts import redirect, render

from ..forms import PostModelForm, PostCreate

all = (
    'post_create',
    'post_create_with_form',
)

User = get_user_model()

def post_create(request):
    # PostModelForm을 사용
    # form = PostModelForm(request.POST, request.FILES)
    # form.save()
    if request.method == 'POST':
        print('POST')
        form = PostModelForm(request.POST, request.FILES)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.save()
            return redirect('index')
    else:
        form = PostModelForm()
        context = {
            'form': form,
        }
        return render(request, 'posts/post_create.html', context)

    @login_required
    def post_create_with_form(request):
        if request.method == 'POST':
            form = PostCreate(request.POST, request.FILES)
            print(request.POST, request.FILES)
            if form.is_valid():
                form.create_post(request.user)
                return redirect('index')
            print('valid false')
        else:
            form = PostCreate()

        context = {
            'form': form,
        }
        return render(request, 'posts/post_create.html', context)

app/posts/views/post_delete.py
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from django.core.exceptions import PermissionDenied
from django.shortcuts import get_object_or_404, redirect
from django.views.decorators.http import require_POST

from posts.models import Post

all = (
    'post_delete',
)

User = get_user_model()

@require_POST
@login_required
def post_delete(request, pk):
    post = get_object_or_404(Post, pk=pk)
    if post.author != request.user:
        raise PermissionDenied('지울 권한이 없습니다')
    post.delete()
    return redirect('posts:post-list')

app/posts/views/post_detail.py
from django.contrib.auth import get_user_model
from django.shortcuts import render

from ..models import Post

all = (
    'post_detail',
)

User = get_user_model()
def post_detail(request, pk):
    post = Post.objects.get(id=pk)
    context = {
        'post': post,
    }
    return render(request, 'posts/post_detail.html', context)

app/posts/views/post_like.py
from django.contrib.auth import get_user_model
from django.shortcuts import redirect

from ..models import Post, PostLike

all = (
    'post_like',
)

User = get_user_model()
def post_like(request, pk):
    if request.method == 'POST':
        post = Post.objects.get(pk=pk)
        try:
            post_like = PostLike.objects.get(user=request.user, post=post)
            post_like.delete()
        except PostLike.DoesNotExist:
            PostLike.objects.create(user=request.user, post=post)

    return redirect('posts:post-list')

app/posts/views/post_list.py
from django.contrib.auth import get_user_model
from django.shortcuts import render

from ..models import Post

all = (
    'post_list'
)

User = get_user_model()
def post_list(request):
    posts = Post.objects.all()
    try:
        following = request.user.following
    except AttributeError:
        following = []
    context = {
        'posts': posts,
        'following':following,
    }
    return render(request, 'posts/post_list.html', context)

app/templates/posts/base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
{% block content %}
{% endblock %}
</body>
</html>

app/templates/posts/post_create.html
{% extends 'base.html' %}

{% block content %}
<div>
    <form action="" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form }}
        {#    {{ form.non_field_errors }}#}
{#        {% csrf_token %}#}
{#        {% for field in form %}#}
{#            <div class="form-group">#}
{#            {{ field.label_tag }} {{ field }}#}
{#            {{ field.errors }}#}
{#                {% if field.help_text %}#}
{#                <p>{{ field.help_text|safe }}</p>#}
{#                {% endif %}#}
{#            </div>#}
{#        {% endfor %}#}
        <button type="submit" class="btn btn-primary btn-block">사진업로드</button>
    </form>
</div>

{% endblock %}

app/templates/posts/post_detail.html
{% extends 'base.html' %}

{% block content %}
<h1>Post Detail</h1>

<p><img src="../../media/{{ post.photo }}" alt="" width="300" height="300"></p>
<p>작성자 : {{ post.author }}</p>
<p>내용 : {{ post.content }}</p>

<a href="{% url 'posts:post-list' %}">뒤로가기</a>
{% endblock %}

app/templates/posts/post_list.html
{% extends 'base.html' %}

{% block content %}
    <div class="">
        <a href="{% url 'posts:post-create' %}">
            <button class="btn btn-primary">사진 업로드</button>
        </a>
    </div>

    <br>
    {% for post in posts %}

        <div class="card border-dark mb-3 mx-auto" style="max-width: 600px;">
            <div class="card-header">
                {% if post.author.img_profile %}
                    <img class="rounded-circle" src="{{ post.author.img_profile.url }}" alt="" width="40" height="40">
                {% else %}
                    {% load static %}
                    <img class="rounded-circle" src="{% static "images/blank_user.png" %}" alt="" width="40"
                         height="40">
                {% endif %}
                <a href="{% url 'members:user-info' post.author_id %}">{{ post.author.username }}</a>
                {# follow 기능 #}
                {% if not user == post.author %}
                    <form action="{% url 'members:follow' post.author_id %}" method="POST"
                          style="display: inline-block;">
                        {% csrf_token %}
                        {% if post.author in following %}
                            <button class="btn btn-primary">unfollow</button>
                        {% else %}
                            <button class="btn btn-primary">follow</button>
                        {% endif %}
                    </form>
                {% endif %}
                <div class="float-right">{% if post.author == user %}
                    <form action="{% url 'posts:post-delete' post.id %}" method="POST">
                        {% csrf_token %}
                        <button class="btn btn-primary">삭제하기</button>
                    </form>
                {% endif %}</div>
            </div>
            <div class="card-body text-dark">
                <a href="{% url 'posts:post-detail' post.id %}"><img src="{{ post.photo.url }}" alt=""
                                                                     class="card-img-top" width="500" height="500"></a>
            </div>
            <div class="mx-sm-4"><strong>{{ post.postlike_set.all|length }} likes</strong>
                <form action="{% url 'posts:post-like' post.id %}" method="POST">
                    {% csrf_token %}
                    {% if user in post.like_users %}
                        <button class="btn btn-primary btn-sm">좋아요 취소</button>
                    {% else %}
                        <button class="btn btn-primary btn-sm" value="{{ post.id }}">좋아요</button>
                    {% endif %}
                </form>
            </div>
            <div class="mx-sm-4">
                <p><strong>{{ post.author }}</strong> {{ post.content }}</p></div>
            <div class="mx-sm-4">
                {% for comment in post.comments.all %}
                    <p><strong>{{ comment.user }}</strong> {{ comment.comment }}</p>
                {% endfor %}</div>
            <form action="{% url 'posts:comment-create' post.id %}" method="POST">
                {% csrf_token %}
                <div class="mx-sm-4 form-row mb-4">
                    <div class="col-9">
                        <input type="text" class="form-control" name="comment">
                    </div>
                    <div class="col">
                        <button class="btn btn-primary">댓글 남기기</button>
                    </div>
                </div>
            </form>
        </div>
    {% endfor %}
{% endblock %}