app/config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from config import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('posts/', include('posts.urls')),
    path('', views.index, name='index'),
    path('members/', include('members.urls')),
] + static(
    prefix='/media/',
    document_root=settings.MEDIA_ROOT,
    )

app/members/urls.py
from django.urls import path

from members import views

app_name = 'members'
urlpatterns = [
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('signup/', views.signup, name='signup'),
    path('<int:pk>/my_info', views.my_info, name='my-info'),
    path('<int:pk>/user_info', views.user_info, name='user-info'),
    path('<int:pk>/withdraw/', views.withdraw, name='withdraw'),
    path('<int:pk>/follow_toggle', views.follow_toggle, name='follow'),
    path('<int:pk>/user_info/followers', views.follower_list, name='followers'),
    path('<int:pk>/user_info/followings', views.following_list, name='followings')

]

app/posts/urls.py
from django.urls import path

from posts import views

app_name = 'posts'
urlpatterns = [
    path('', views.post_list, name='post-list'),
    path('<int:pk>/', views.post_detail, name='post-detail'),
    path('post_create/', views.post_create, name='post-create'),
    path('<int:pk>/post_delete/', views.post_delete, name='post-delete'),
    path('<int:pk>/comment_create/', views.comment_create, name='comment-create'),
    path('<int:pk>/post_like', views.post_like, name='post-like'),

]

app/members/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

from members.exception import RelationNotExist, DuplicateRelationException


class User(AbstractUser):
    CHOICE_GENDER = (
        ('m', '남성'),
        ('f', '여성'),
        ('x', '선택안함')
    )
    img_profile = models.ImageField(upload_to='user', blank=True)
    site = models.URLField(blank=True)
    introduce = models.TextField(blank=True)
    gender = models.CharField(max_length=1, choices=CHOICE_GENDER)
    to_relation_users = models.ManyToManyField(
        'self',
        through='Relation',
        symmetrical=False,
        blank=True,
        related_name='from_relation_users',
        related_query_name='from_relation_user',
    )

    def __str__(self):
        return self.username


    @property
    def following(self):
        return User.objects.filter(
            relation_by_to_user__from_user=self,
            relation_by_to_user__relation_type=Relation.RELATION_TYPE_FOLLOW,
        )

    @property
    def followers(self):
        return User.objects.filter(
            relation_by_from_user__to_user=self,
            relation_by_from_user__relation_type=Relation.RELATION_TYPE_FOLLOW,
        )

    # @property
    # def block_user(self):
    #     return User.objects.filter(
    #         relation_by_from_user__to_user=self,
    #         relation_by_from_user__relation_type=Relation.RELATION_TYPE_BLOCK,
    #     )

    @property
    def following_relations(self):
        return self.relation_by_from_user.filter(
            relation_type=Relation.RELATION_TYPE_FOLLOW,
        )

    @property
    def follower_relations(self):
        return self.relation_by_to_user.filter(
            relation_type=Relation.RELATION_TYPE_FOLLOW,
        )

    @property
    def block_relations(self):
        return self.relation_by_to_user.filter(
            relation_type=Relation.RELATION_TYPE_BLOCK,
        )

    def follow(self, to_user):


        if self.relation_by_from_user.filter(
            to_user__in=to_user).exists():
            raise DuplicateRelationException(from_user=self,to_user=to_user,relation_type='follow')

        return self.relation_by_from_user.create(
            to_user=to_user,
            relation_type=Relation.RELATION_TYPE_FOLLOW,
        )

    def unfollow(self, to_user):
        q = self.relation_by_from_user.filter(
            to_user=to_user,
            relation_type=Relation.RELATION_TYPE_FOLLOW
        )

        if q:
            q.delete()
        else:
            raise RelationNotExist(
                from_user=self,
                to_user=to_user,
                relation_type='Follow',
            )

class Relation(models.Model):
    RELATION_TYPE_BLOCK = 'b'
    RELATION_TYPE_FOLLOW = 'f'
    CHOICES_RELATION_TYPE = (
        (RELATION_TYPE_FOLLOW, 'Follow'),
        (RELATION_TYPE_BLOCK, 'Block',),
    )
    from_user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='relation_by_from_user'
    )
    to_user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='relation_by_to_user'
    )
    relation_type = models.CharField(max_length=1, choices=CHOICES_RELATION_TYPE)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        unique_together = (
            ('from_user', 'to_user'),
        )

    def __str__(self):
        return 'From {from_user} to {to_user} ({type})'.format(
            from_user=self.from_user.username,
            to_user=self.to_user.username,
            type=self.get_relation_type_display()
        )

app/members/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.core.exceptions import ValidationError

from members.views import User

User = get_user_model()

class SignupForm(forms.Form):
    img_profile = forms.ImageField(
        label='프로필 사진',
        widget=forms.ClearableFileInput(
            attrs={
                'class':'form-control',
            },
        )
    )

    username = forms.CharField(label='아이디', widget=forms.TextInput(
        attrs={
            'class': 'form-control',
        }
    ))
    password = forms.CharField(label='패스워드', widget=forms.PasswordInput(
        attrs={
            'class': 'form-control',
        }
    ))
    password2 = forms.CharField(label='패스워드 확인', widget=forms.PasswordInput(
        attrs={
            'class': 'form-control',
        }
    ))
    email = forms.EmailField(label='이메일', widget=forms.TextInput(
        attrs={
            'class':'form-control',
        }
    ))

    introduce = forms.CharField(label='소개', widget=forms.Textarea(
        attrs={
            'class':'form-control',
        }
    ))
    gender = forms.CharField(
        label='성별',
        widget=forms.Select(
            attrs={
                'class':'form-control',
            },
            choices=User.CHOICE_GENDER,
        )
    )
    site = forms.CharField(
        label='사이트', widget=forms.TextInput(
        attrs={
            'class':'form-control',
        }
    ))
    def clean_username(self):

        username = self.cleaned_data['username']
        if User.objects.filter(username=username).exists():
            raise ValidationError('아이디가 이미 존재합니다')
        return username


    def clean(self):
        super().clean()
        password = self.cleaned_data.get("password")
        password2 = self.cleaned_data.get("password2")
        if password != password2:

            self.add_error('password2','비밀번호가 다릅니다')
        return self.cleaned_data

    def signup(self):
        fields = [
            'username',
            'email',
            'password',
            'gender',
            'img_profile',
            'introduce',
            'site'
        ]
        # create_user_dict = {}
        # for field in fields:
        #     create_user_dict[field]=self.cleaned_data[field]
        #
        # print(create_user_dict)

        # create_user_dict = {key : value for key, value in self.cleaned_data.items() if key in fields}
        # def in_fields(item):
        #     return item[0] in fields
        #
        # result = filter(in_fields, self.cleaned_data.items())
        # for item in result:
        #     print(item)
        #     print(type(item))

        create_user_dict = dict(filter(lambda item: item[0] in fields, self.cleaned_data.items()))
        # print(create_user_dict)
        # print(self.cleaned_data)
        # self.cleaned_data.pop('password2')
        # print(self.cleaned_data)
        user = User.objects.create_user(**create_user_dict)
        # img_profile = self.cleaned_data['img_profile']
        # username = self.cleaned_data['username']
        # email = self.cleaned_data['email']
        # password = self.cleaned_data['password']
        # introduce = self.cleaned_data['introduce']
        # gender = self.cleaned_data['gender']
        #
        # user = User.objects.create_user(
        #     img_profile=img_profile,
        #     username=username,
        #     email=email,
        #     password=password,
        #     introduce=introduce,
        #     gender=gender,
        # )
        return user

app/members/views.py
from django.contrib.auth import authenticate, login, get_user_model, logout
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, redirect

# User클래스 자체를 가져올때는 get_user_model()
# ForeignKey에 User모델을 지정할때는 settings.AUTH_USER_MODEL
from members.models import Relation

User = get_user_model()


def login_view(request):

    # 1. member.urls <- 'members/'로 include되도록 config.urls모듈에 추가
    # 2. path구현 (URL: '/members/login/')
    # 3. path와 이 view연결
    # 4. 일단 잘 나오는지 확인
    # 5. 잘 나오면 form을 작성 (username, password를 받는 input2개)
    #   templates/members/login.html에 작성

    # 6. form작성후에는 POST방식 요청을 보내서 이 뷰에서 request.POST에 요청이 잘 왔는지 확인
    # 7. 일단은 받은 username, password값을 HttpResponse에 보여주도록 한다.
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        print(request.user.is_authenticated)
        # 받은 username과 password에 해당하는 User가 있는지 인증
        user = authenticate(request, username=username, password=password)

        # 인증에 성공한 경우
        if user is not None:
            # 세션값을 만들어 DB에 저장하고, HTTP response의 Cookie에 해당값을 담아보내도록 하는
            # login()함수를 실행한다
            login(request, user)
            next = request.GET.get('next')
            if next:
                return redirect(next)
            return redirect('posts:post-list')
        # 인증에 실패한 경우 (username또는 password가 틀린 경우)
        else:
            # 다시 로그인 페이지로 redirect
            return redirect('members:login')
    # GET 요청일 경우
    else:
        # form이 있는 template을 보여준다
        # if request.GET['next']:
        #     return redirect(request.GET['next'])
        # print(request.GET['next'])

        return render(request, 'members/login.html')


def logout_view(request):
    logout(request)
    return redirect('index')


from .forms import SignupForm


def signup(request):
    if request.method == 'POST':
        form = SignupForm(request.POST, request.FILES)
        if form.is_valid():
            user = form.signup()
            login(request, user)
            return redirect('index')
    else:
        form = SignupForm()

    context = {
        'form': form,
    }
    return render(request, 'members/signup.html', context)


def signup_bak(request):
    context = {
        'errors': [],
    }
    if request.method == 'POST':
        # username, email, password, password2에 대해서
        # 입력되지 않은 필드에 대한 오류를 추가
        username = request.POST['username']
        email = request.POST['email']
        password = request.POST['password']
        password2 = request.POST['password2']

        # 반드시 내용이 채워져야 하는 form의 필드 (위 변수명)
        # hint: required_fields를 dict로
        # required_fields = ['username', 'email', 'password', 'password2']
        required_fields = {
            'username': {
                'verbose_name': '아이디',
            },
            'email': {
                'verbose_name': '이메일',
            },
            'password': {
                'verbose_name': '비밀번호',
            },
            'password2': {
                'verbose_name': '비밀번호 확인',
            },
        }
        for field_name in required_fields.keys():
            if not locals()[field_name]:
                context['errors'].append('{}을(를) 채워주세요'.format(
                    required_fields[field_name]['verbose_name'],
                ))


        # 입력데이터 채워넣기
        context['username'] = username
        context['email'] = email



        # errors가 없으면 유저 생성 루틴 실행
        if not context['errors']:
            user = User.objects.create_user(
                username=username,
                password=password,
                email=email,
            )
            login(request, user)
            return redirect('index')
    return render(request, 'members/signup.html', context)

def my_info(request, pk):
    user = User.objects.get(pk=pk)
    context = {
        'user':user,
    }
    return render(request, 'members/my_info.html', context)

def user_info(request, pk):
    insta_user = User.objects.get(pk=pk)
    context = {
        'insta_user':insta_user,
    }
    return render(request, 'members/user_info.html', context)

def withdraw(request, pk):
    user = User.objects.get(pk=pk)
    user.delete()
    return redirect('index')

def follow_toggle(request, pk):
    if request.method == 'POST':
        to_user = User.objects.get(pk=pk)
        try:
            print('get and delete')
            follow = Relation.objects.get(from_user=request.user, to_user=to_user)
            follow.delete()

        except :
            print('create')
            Relation.objects.create(from_user=request.user, to_user=to_user, relation_type='f')
    return redirect(request.META['HTTP_REFERER'])

def follower_list(request, pk):
    insta_user = User.objects.get(pk=pk)
    followers = insta_user.followers
    context = {
        'insta_user':insta_user,
        'followers':followers,
    }
    return render(request, 'members/follower_list.html', context)

def following_list(request, pk):
    insta_user = User.objects.get(pk=pk)
    followings = insta_user.following
    context = {
        'insta_user': insta_user,
        'followings': followings,
    }
    print(context)
    return render(request, 'members/following_list.html', context)

app/templates/members/follower_list.html
{% extends 'base.html' %}
{% block content %}
    <h1>Follower List</h1>

    {% for follower in followers %}
        {% if follower in user.followers %}
            <form action="{% url 'members:follow' insta_user.id %}" method="POST"
                  style="display: inline-block;">
                {% csrf_token %}
                {% if follower in user.followers %}
                    <p>{{ follower }}
                        <button class="btn btn-primary">unfollow</button>
                    </p>
                {% else %}
                    <p>{{ follower }}
                        <button class="btn btn-primary">follow</button>
                    </p>
                {% endif %}
            </form>
        {% endif %}
    {% endfor %}

{% endblock %}

app/templates/members/following_list.html
{% extends 'base.html' %}
{% block content %}
    <h1>Following List</h1>

    {% for following in followings %}

        <form action="{% url 'members:follow' insta_user.id %}" method="POST"
                  style="display: inline-block;">
                {% csrf_token %}
                {% if following in user.following %}
                    <p>{{ following }}
                        <button class="btn btn-primary">unfollow</button>
                    </p>
                {% else %}
                    <p>{{ following }}
                        <button class="btn btn-primary">follow</button>
                    </p>
                {% endif %}
            </form>
    {% endfor %}

{% endblock %}

app/templates/members/login.html
{% extends 'base.html' %}

{% block title %}Log In{% endblock %}

{% block content %}
<div class="container" style="margin-top: 30px;">
    <form action="" method="POST">
        {% csrf_token %}
        <div class="login-window">
            <div class="input-group mb-3" style="width: 400px;">
            <div class="input-group-prepend" style="width: 120px;">
                <span class="input-group-text" id="inputGroup-sizing-default" style="width: 120px;">아이디</span>
            </div>
            <input type="text" class="form-control" aria-label="Default" aria-describedby="inputGroup-sizing-default" name="username">
        </div>
            <div class="input-group mb-3" style="width: 400px;">
            <div class="input-group-prepend" style="width: 120px;">
                <span class="input-group-text" id="inputGroup-sizing-default" style="width: 120px;">패스워드</span>
            </div>
            <input type="password" class="form-control" aria-label="Default" aria-describedby="inputGroup-sizing-default" name="password">
        </div>
            <button type="submit" class="btn btn-light">로그인하기</button>
        </div>
    </form>
</div>
{% endblock %}

app/templates/members/my_info.html
{% extends 'base.html' %}

{% block content %}
    <a href="{% url 'members:followers' user.id %}">
        <button class="btn btn-primary">팔로워 보기</button>
    </a>
    <a href="{% url 'members:followings' user.id %}">
        <button class="btn btn-primary">팔로잉 보기</button>
    </a>
    <ul>
        <li>{{ user.username }}</li>
        <li>{{ user.img_profile }}</li>
    <li>{{ user.email }}</li>
    <li>{{ user.introduce }}</li>
    <li>{{ user.get_gender_display }}</li>
    <li>{{ user.site }}</li>
    </ul>
    <form action="{% url 'members:withdraw' user.id %}" method="POST">
    {% csrf_token %}
    <button class="btn btn-primary">회원탈퇴</button>
    </form>
{% endblock %}

app/templates/members/signup.html
{% extends 'base.html' %}
{% block content %}
<div>
    <form action="" method="POST">
    {{ form.non_field_errors }}
        {% csrf_token %}
        {% for field in form %}
            <div class="form-group">

            {{ field.label_tag }} {{ field }}
            {{ field.errors }}
                {% if field.help_text %}
                <p>{{ field.help_text|safe }}</p>
                {% endif %}
            </div>
        {% endfor %}
        <button type="submit" class="btn btn-primary btn-block">회원가입</button>
    </form>
</div>
{% endblock %}

app/templates/members/signup_bak.html
{% extends 'base.html' %}

{% block content %}
    {% if messages %}
        {%  for message in messages %}
            {{  message }}
        {% endfor %}
    {% endif %}
<ul>
    {% for error in errors %}
       <li>{{  error }}</li>
    {% endfor %}
</ul>
<div>
    <form action="" method="POST">
        {% csrf_token %}
            <p><label for="">이름 </label><input type="text" name="username" value="{{ username }}"></p>
            <p><label for="">패스워드</label><input type="password" name="password" value=""></p>
            <p><label for="">패스워드 확인</label><input type="password" name="password2"></p>

            <p><label for="">이메일 </label><input type="text" name="email" value="{{ email }}"></p>
            <p><label for="">핸드폰</label><input tye="text" name="phone_no" value="{{ phone_no }}"></p>
            <p>
                <button type="submit">가입하기</button>
            </p>
    </form>
</div>
{% endblock %}

app/templates/members/user_info.html
{% extends 'base.html' %}

{% block content %}
    <a href="{% url 'members:followers' insta_user.id %}">
        <button class="btn btn-primary">팔로워 보기</button>
    </a>
    <a href="{% url 'members:followings' insta_user.id %}">
        <button class="btn btn-primary">팔로잉 보기</button>
    </a>
    <ul>
        <li>{{ insta_user.username }}</li>
        <li>{{ insta_user.img_profile }}</li>
        <li>{{ insta_user.email }}</li>
        <li>{{ insta_user.introduce }}</li>
        <li>{{ insta_user.get_gender_display }}</li>
        <li>{{ insta_user.site }}</li>
    </ul>
{% endblock %}