app/config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from config import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('posts/', include('posts.urls')),
    path('', views.index, name='index'),
    path('members/', include('members.urls')),
] + static(
    prefix='/media/',
    document_root=settings.MEDIA_ROOT,
    )

app/members/urls.py
from django.urls import path

from members import views

app_name = 'members'
urlpatterns = [
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('signup/', views.signup, name='signup'),
    path('<int:pk>/my_info', views.my_info, name='my-info'),
    path('<int:pk>/user_info', views.user_info, name='user-info'),
    path('<int:pk>/withdraw/', views.withdraw, name='withdraw'),
    path('<int:pk>/follow_toggle', views.follow_toggle, name='follow'),
    path('<int:pk>/user_info/followers', views.follower_list, name='followers'),
    path('<int:pk>/user_info/followings', views.following_list, name='followings')

]

app/posts/urls.py
from django.urls import path

from posts import views

app_name = 'posts'
urlpatterns = [
    path('', views.post_list, name='post-list'),
    path('<int:pk>/', views.post_detail, name='post-detail'),
    path('post_create/', views.post_create, name='post-create'),
    path('<int:pk>/post_delete/', views.post_delete, name='post-delete'),
    path('<int:pk>/comment_create/', views.comment_create, name='comment-create'),
    path('<int:pk>/post_like', views.post_like, name='post-like'),

]

app/templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Instagram</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous">
</head>
<body>
<div class="container">
    <h1><a href="{% url 'index' %}">Instagram</a></h1>
    <div>
        {% if user.is_authenticated %}
        <p><a href="{% url 'members:my-info' user.id %}">{{ user }}</a>님 환영합니다.
        <form action="{% url 'members:logout' %}" method="POST">
        {% csrf_token %}
        <button type="submit" class="btn btn-light">로그아웃하기</button>
    </form></p>
        {% else %}
        <a href="{% url 'members:login' %}">
            <button class="btn btn-primary">로그인하기</button></a>
        <a href="{% url 'members:signup' %}"><button class="btn btn-primary">회원가입</button>
    </a>
        {% endif %}
    </div>
    {% block content %}
    {% endblock %}
</div>
</body>
</html>